name: speakly
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI
  flutter_easyloading: ^3.0.5
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.17
  gap: ^3.0.1

  # Animation
  loading_animation_widget: ^1.3.0
  bounce: ^1.0.2

  # Helpers
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  mask_text_input_formatter: ^2.9.0
  image_picker: ^1.1.2
  flutter_exif_rotation: ^0.5.2
  fpdart: ^1.1.1
  fluttertoast: ^8.2.12
  permission_handler: ^11.3.1

  # google-speech
  google_speech: ^5.3.0
  flutter_sound: ^9.23.1
  path_provider: ^2.1.5
  flutter_tts: ^4.2.2

  # State management
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  dio: ^5.7.0
  retrofit: ^4.4.2
  requests_inspector: ^4.2.0
  ota_update: ^6.0.0

  # Localization
  easy_localization: ^3.0.7

  # Navigation
  go_router: ^14.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/
    - assets/google-speech/google.json
    - assets/images/
    - .env
    
  
  fonts:
    - family: Samsung
      fonts:
        # - asset: assets/fonts/Stolzl-Regular.ttf
        - asset: assets/fonts/Samsung.ttf
